### ISSUE TITLE
Add a tab that will list every issues that on the osscameroon github organisation

### ISSUE THREAD

**Issue by elhmn** [osscameroon/miniyotas#15]
We need to add a new tab that will list every Issues available on the osscameroon GitHub organisation. 
The Issues tagged with a Yotas label should be listed at the top of the list and ordered from the lowest number of Yotas to the higher at the bottom.

**Comment by valerymelou** [comment]
I guess for this we need to go through the GitHub API. Do we already have an OSS Cameroon oAuth app that has access to the API or this is the first time the access will be configured?

**Comment by elhmn** [comment]
> I guess for this we need to go through the GitHub API. Do we already have an OSS Cameroon oAuth app that has access to the API or this is the first time the access will be configured?

You won't need it anymore as I have created a GitHub Action that creates a [file](https://github.com/osscameroon/miniyotas/blob/main/src/res/osscameroon_issues.json) with the osscameroon issues for you, now you probably would like to read the content of this file and display it on the web UI.

If you are curious here are the PRs (#19  and #20) that did the job, hope this helps. 🙇‍♂️

**Comment by elhmn** [comment]
Closing as it is resolved by #21
