### ISSUE TITLE
The current page is not highlighted

### ISSUE THREAD

**Issue by elhmn** [osscameroon/miniyotas#24]
When a user is on page `N` the pagination does not highlight page N.

We could add a background color to the `Nth` page button.

https://user-images.githubusercontent.com/5704817/162693525-a547453d-021c-4b60-beae-93659810697e.mp4

**Comment by Blanco237** [comment]
Has this issue been solved, considering someone was assigned to it on the 24th of April...

**Comment by sikatikenmogne** [comment]
Hi @elhmn,

I’m a new contributor from the OSSCameroon group chat and came across this issue via the OSSCameroon bot on Telegram.

I’ve been working on a potential solution and have a branch with the changes. You can check it out here: [https://github.com/sikatikenmogne/miniyotas/tree/feat/add-highlightning-on-pagination](https://github.com/sikatikenmogne/miniyotas/tree/feat/add-highlightning-on-pagination).

In this branch, I’ve added a background color to the current page button to make it more noticeable and fix an error about `yarn dev` on windows. I’d appreciate any feedback on this approach and would like to know if it’s okay to create a pull request with these changes.

Looking forward to your feedback!

Best,
