### ISSUE TITLE
Issue with proxy forwarder

### ISSUE THREAD

**Issue by pythonbrad** [osscameroon/miniyotas#36]
### Problem
I deployed the website on a container, and experienced a problem when clicking on the pagination.
I have been redirected to `http://localhost:3000/?query=&sort=yotas_desc&page=1`, who is not normal.

### Expected behavior
Be redirected to `https://potential-meme-xxxxxxx-3000.app.github.dev/?query=&sort=yotas_desc&page=1`

### Test environment
GitHub codespace.

### Possible solution
- remove full absolute URL build in `src/views/partials/pagination.hbs`.

**Comment by sikatikenmogne** [comment]
Hi @pythonbrad,

In response to your issue, I’ve added a new helper function called `removeDomain` that parses and cleans URLs by removing the domain part. This function is now used in the `constructUrl` helper to ensure that URLs are properly formatted. Additionally, I’ve updated the `pagination.hbs` template to utilize this new helper, which should resolve the issue of incorrect redirections.

You can review the changes in the pull request linked above (#37). With these updates, you should now be redirected to the correct URL in the pagination component. Please let me know if this resolves the issue or if any further adjustments are needed.

Best regards,
