### ISSUE TITLE
implement pagination for list of contributors

### ISSUE THREAD

**Issue by elhmn** [osscameroon/miniyotas#4]
later the list of contributors might be bigger and it would be nice to have a pagination just to make nicer to read

The pagination was already implemented on [camerapps](https://camerapps.com) whose code base is located [here](https://github.com/osscameroon/camerapps.com)
<img width="1329" alt="Screenshot 2021-12-23 at 08 58 49" src="https://user-images.githubusercontent.com/5704817/147208077-3e552d06-f0fb-4b3c-bcbc-afa83df611a6.png">

It is now a matter of copying and pasting that functionality from the camerapps code base and integrate it here.

**Comment by valerymelou** [comment]
Which list are we talking about please? Could we please have the link where it is displayed?

**Comment by elhmn** [comment]
Sorry for the late reply, I did not see your message. I referred to the list of contributors that you can see the image bellow.

<img width="1326" alt="Screenshot 2021-12-23 at 08 57 53" src="https://user-images.githubusercontent.com/5704817/147207859-0a829d5c-cde0-426b-8c90-2236eb0580e0.png">

The pagination was already implemented on [camerapps](https://camerapps.com) whose code base is located [here](https://github.com/osscameroon/camerapps.com)
<img width="1329" alt="Screenshot 2021-12-23 at 08 58 49" src="https://user-images.githubusercontent.com/5704817/147208077-3e552d06-f0fb-4b3c-bcbc-afa83df611a6.png">

**Comment by valerymelou** [comment]
Thanks. I was able to find the page and implement the pagination. Could you please check my PR #17 ?

**Comment by elhmn** [comment]
Resolved by #17
