### ISSUE TITLE
Add sort by select button

### ISSUE THREAD

**Issue by elhmn** [osscameroon/miniyotas#7]
We might want to sort users by the ascending or descending amount of yotas they possess.

**Comment by Dorian21-prog** [comment]
Please can you explain more about this issue?

**Comment by elhmn** [comment]
Currently the list of contributors is sorted alphabetically. As you can see on the image below. We would like to have that list sorted using the number of yotas each user has. Users having the greatest amount of Yotas will be at the top of the list.

![image](https://github.com/osscameroon/miniyotas/assets/5704817/e6095a9c-3256-411f-9a64-a8920235567b)

Hope that can help, and let me know if I can do anything else for you

**Comment by noumendarryl** [comment]
Hi @elhmn,

I’m a new contributor from the OSSCameroon group chat and came across this issue via the OSSCameroon bot on Telegram.

I’ve been working on a potential solution and have a branch with the changes. You can check it out here: https://github.com/noumendarryl/miniyotas/tree/feat/sorting.

In this branch, I’ve added all what I thought was needed to implement this feature. I’d appreciate any feedback on this approach and would like to know if it’s okay to create a pull request with these changes.

Looking forward to your feedback!

Best,

**Comment by rakici** [comment]
Closed by https://github.com/osscameroon/miniyotas/pull/35
